#!/usr/bin/env bash

chflags nohidden ~/Library
chflags nohidden ~/Applications

ln -s ~/.infrastructure/bin ~/bin
ln -s ~/.infrastructure/bash ~/.bash
ln -s ~/.infrastructure/bashrc ~/.bashrc
ln -s ~/.infrastructure/profile ~/.profile
source ~/.profile

ln -s ~/.infrastructure/janus ~/.janus
ln -s ~/.infrastructure/vimrc.after ~/.vimrc.after
ln -s ~/.infrastructure/gvimrc.after ~/.gvimrc.after
ln -s ~/.infrastructure/gitconfig ~/.gitconfig
ln -s ~/.infrastructure/irbrc ~/.irbrc

ITERM="$HOME/Library/Application Support/iTerm"
ln -s ~/.infrastructure/Desert.itermcolors "$ITERM/Desert.itermcolors"

rbenv install 2.1.3
rbenv global 2.1.3
rbenv rehash
