#!/usr/bin/env bash

chflags nohidden ~/Library
chflags nohidden ~/Applications

ln -s ~/.infrastructure/bin ~/bin
ln -s ~/.infrastructure/bash ~/.bash
ln -s ~/.infrastructure/bashrc ~/.bashrc
ln -s ~/.infrastructure/profile ~/.profile
source ~/.profile

ln -s ~/.infrastructure/vimrc.after ~/.vimrc.after
ln -s ~/.infrastructure/gvimrc.after ~/.gvimrc.after
ln -s ~/.infrastructure/gitconfig ~/.gitconfig

LIMECHAT="$HOME/Library/Application Support/LimeChat/Themes"
ln -s ~/.infrastructure/LimeChat/limescripts "$LIMECHAT/limescripts"

ln -s ~/.infrastructure/LimeChat/mosey-limechat-theme/mosey.css "$LIMECHAT/mosey.css"
ln -s ~/.infrastructure/LimeChat/mosey-limechat-theme/mosey.yaml "$LIMECHAT/mosey.yaml"
ln -s "$LIMECHAT/limescripts/limescripts.js" "$LIMECHAT/mosey.js"

ln -s ~/.infrastructure/LimeChat/Hipchat/Hipchat.css "$LIMECHAT/Hipchat.css"
ln -s ~/.infrastructure/LimeChat/Hipchat/Hipchat.yaml "$LIMECHAT/Hipchat.yaml"
ln -s "$LIMECHAT/limescripts/limescripts.js" "$LIMECHAT/Hipchat.js"

ITERM="$HOME/Library/Application Support/iTerm"
ln -s ~/.infrastructure/Desert.itermcolors "$ITERM/Desert.itermcolors"

rbenv install 1.8.7-p370

## Ruby 1.9.3-p392-railsexpress
export CFLAGS="-march=core2 -O3 -pipe -fomit-frame-pointer"
curl https://raw.github.com/gist/4646193/rbenv.sh | sh

rbenv global 1.9.3-p392-railsexpress
rbenv rehash
